apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: sentrionic/user-service
          env:
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: session-secret
                  key: SESSION_SECRET
            - name: PORT
              value: "4000"
            - name: COOKIE_NAME
              value: "sgl"
            - name: DATABASE_URL
              value: 'postgresql://root:password@user-postgres-srv:5432/signal?sslmode=disable'
            - name: RABBIT_MQ_URI
              value: 'amqp://rabbitmq-srv:5672'
            - name: SESSION_DURATION
              value: "86400000" # 1000 * 60 * 60 * 24 = 1 Day
            - name: NODE_ENV
              value: 'development'
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user-service
  ports:
    - name: user-service
      protocol: TCP
      port: 4000
      targetPort: 4000