name: "[MediaService] Run Lint"

defaults:
  run:
    working-directory: ./media-service

on:
  push:
    paths:
      - 'media-service/**'
  pull_request:
    paths:
      - 'media-service/**'

jobs:
  linter:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
          cache-dependency-path: media-service/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build server
        run: pnpm build

      - name: Eslint check
        run: pnpm lint